### ISSUE TITLE
OSX EL Capitan

### ISSUE THREAD

**Issue by misfotto** [drego85/JoomlaScan#1]
On OSX ( El Capitan ) BeautifulSoup4 is needed:

```
sudo pip install beautifulsoup4
```

if you don't have pip installed:

```
curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
```

:)

**Comment by drego85** [comment]
Thanks, I forgot to specify it in the README.

I’ve update the file.
